package day7

import (
	"testing"
)

func TestSample(t *testing.T) {
	sampleData := `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`

	ans1, ans2 := Solve(sampleData)
	if ans1 != 21 {
		t.Fatalf("Mismatch! Expected 21 got %d", ans1)
	}
	if ans2 != 40 {
		t.Fatalf("Mismatch! Expected 40 got %d", ans2)
	}
}
